version: "3.7"

services:
  jekyll_site:
    # ↓バージョン指定しないと動作しない
    # https://github.com/jekyll/jekyll/issues/9066
    image: jekyll/jekyll:4.2.0
    command: ["jekyll", "serve"]
    ports:
      - "4000:4000"
    volumes:
     - type: bind
       source: .
       target: /srv/jekyll